version: '3'
services:
  app:
    build: .
    restart: on-failure
    volumes:
      - .:/go/src/github.com/zdunecki/discountly/
    entrypoint: dlv debug --headless --listen=:2345 --api-version=2
    ports:
      - "4444:4444"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - mongo
      - geo
    env_file:
      - local.env
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
  geo:
    image: tile38/tile38
    ports:
      - 9851:9851
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  mongo:
  redis: