version: '3'
services:
  app:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - mongo
      - geo
    env_file:
      - .env
  mongo:
    image: mongo:3.6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
  geo:
    image: tile38/tile38
    restart: on-failure
  redis:
    image: redis:5.0
    restart: on-failure
    volumes:
      - redis:/data

volumes:
  mongo:
  redis:
